/**
 * Canonical Indian-bank reference list. This is the single source of truth that
 * seeds the `Bank` table on boot (BanksService.onModuleInit); the app fetches it
 * via GET /banks. `code` is the 4-letter IFSC prefix; `acctMin`/`acctMax` are the
 * account-number digit ranges used for client-side validation.
 */
export interface BankSeed {
  code: string;
  name: string;
  acctMin: number;
  acctMax: number;
  acctExample?: string;
  category: 'public' | 'private' | 'sfb' | 'payments' | 'foreign' | 'coop';
}

export const BANK_SEED: BankSeed[] = [
  // ── Public sector ──────────────────────────────────────────────────────────
  {
    code: 'SBIN',
    name: 'State Bank of India',
    acctMin: 11,
    acctMax: 17,
    acctExample: '30123456789',
    category: 'public',
  },
  {
    code: 'PUNB',
    name: 'Punjab National Bank',
    acctMin: 16,
    acctMax: 16,
    acctExample: '0123000100123456',
    category: 'public',
  },
  {
    code: 'BARB',
    name: 'Bank of Baroda',
    acctMin: 14,
    acctMax: 14,
    acctExample: '12340100012345',
    category: 'public',
  },
  {
    code: 'CNRB',
    name: 'Canara Bank',
    acctMin: 13,
    acctMax: 13,
    acctExample: '0123101012345',
    category: 'public',
  },
  {
    code: 'UBIN',
    name: 'Union Bank of India',
    acctMin: 15,
    acctMax: 15,
    acctExample: '123401010012345',
    category: 'public',
  },
  {
    code: 'BKID',
    name: 'Bank of India',
    acctMin: 15,
    acctMax: 15,
    acctExample: '123430110012345',
    category: 'public',
  },
  {
    code: 'IDIB',
    name: 'Indian Bank',
    acctMin: 9,
    acctMax: 15,
    acctExample: '1234567890',
    category: 'public',
  },
  {
    code: 'CBIN',
    name: 'Central Bank of India',
    acctMin: 10,
    acctMax: 10,
    acctExample: '1234567890',
    category: 'public',
  },
  {
    code: 'IOBA',
    name: 'Indian Overseas Bank',
    acctMin: 15,
    acctMax: 15,
    acctExample: '123401000012345',
    category: 'public',
  },
  {
    code: 'UCBA',
    name: 'UCO Bank',
    acctMin: 14,
    acctMax: 14,
    acctExample: '01230100012345',
    category: 'public',
  },
  {
    code: 'MAHB',
    name: 'Bank of Maharashtra',
    acctMin: 11,
    acctMax: 11,
    acctExample: '60123456789',
    category: 'public',
  },
  {
    code: 'PSIB',
    name: 'Punjab & Sind Bank',
    acctMin: 15,
    acctMax: 15,
    acctExample: '01231000012345',
    category: 'public',
  },
  {
    code: 'IBKL',
    name: 'IDBI Bank',
    acctMin: 13,
    acctMax: 16,
    acctExample: '0123104000012345',
    category: 'public',
  },

  // ── Private sector ─────────────────────────────────────────────────────────
  {
    code: 'HDFC',
    name: 'HDFC Bank',
    acctMin: 14,
    acctMax: 14,
    acctExample: '50100123456789',
    category: 'private',
  },
  {
    code: 'ICIC',
    name: 'ICICI Bank',
    acctMin: 12,
    acctMax: 12,
    acctExample: '123401500001',
    category: 'private',
  },
  {
    code: 'UTIB',
    name: 'Axis Bank',
    acctMin: 15,
    acctMax: 18,
    acctExample: '912010012345678',
    category: 'private',
  },
  {
    code: 'KKBK',
    name: 'Kotak Mahindra Bank',
    acctMin: 10,
    acctMax: 14,
    acctExample: '1234567890',
    category: 'private',
  },
  {
    code: 'INDB',
    name: 'IndusInd Bank',
    acctMin: 12,
    acctMax: 16,
    acctExample: '123456789012',
    category: 'private',
  },
  {
    code: 'YESB',
    name: 'Yes Bank',
    acctMin: 15,
    acctMax: 18,
    acctExample: '001234567890',
    category: 'private',
  },
  {
    code: 'IDFB',
    name: 'IDFC First Bank',
    acctMin: 11,
    acctMax: 14,
    acctExample: '10012345678',
    category: 'private',
  },
  {
    code: 'FDRL',
    name: 'Federal Bank',
    acctMin: 14,
    acctMax: 14,
    acctExample: '12340100123456',
    category: 'private',
  },
  {
    code: 'RATN',
    name: 'RBL Bank',
    acctMin: 12,
    acctMax: 16,
    acctExample: '123456789012',
    category: 'private',
  },
  {
    code: 'BDBL',
    name: 'Bandhan Bank',
    acctMin: 14,
    acctMax: 14,
    acctExample: '10012345678',
    category: 'private',
  },
  {
    code: 'SIBL',
    name: 'South Indian Bank',
    acctMin: 13,
    acctMax: 16,
    acctExample: '0123012345678',
    category: 'private',
  },
  {
    code: 'KVBL',
    name: 'Karur Vysya Bank',
    acctMin: 13,
    acctMax: 16,
    acctExample: '1234123456789',
    category: 'private',
  },
  {
    code: 'CIUB',
    name: 'City Union Bank',
    acctMin: 15,
    acctMax: 15,
    acctExample: '123456789012345',
    category: 'private',
  },
  {
    code: 'KARB',
    name: 'Karnataka Bank',
    acctMin: 13,
    acctMax: 16,
    acctExample: '1234500012345',
    category: 'private',
  },
  {
    code: 'DCBL',
    name: 'DCB Bank',
    acctMin: 14,
    acctMax: 16,
    acctExample: '12340012345678',
    category: 'private',
  },
  {
    code: 'DLXB',
    name: 'Dhanlaxmi Bank',
    acctMin: 12,
    acctMax: 16,
    acctExample: '001234567890',
    category: 'private',
  },
  {
    code: 'JAKA',
    name: 'Jammu & Kashmir Bank',
    acctMin: 13,
    acctMax: 16,
    acctExample: '0012010012345',
    category: 'private',
  },
  {
    code: 'TMBL',
    name: 'Tamilnad Mercantile Bank',
    acctMin: 12,
    acctMax: 16,
    acctExample: '001234567890',
    category: 'private',
  },
  {
    code: 'CSBK',
    name: 'CSB Bank',
    acctMin: 12,
    acctMax: 16,
    acctExample: '012345678901',
    category: 'private',
  },
  {
    code: 'NTBL',
    name: 'Nainital Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'private',
  },

  // ── Small finance banks ────────────────────────────────────────────────────
  {
    code: 'AUBL',
    name: 'AU Small Finance Bank',
    acctMin: 15,
    acctMax: 16,
    acctExample: '1234123456789',
    category: 'sfb',
  },
  {
    code: 'ESFB',
    name: 'Equitas Small Finance Bank',
    acctMin: 15,
    acctMax: 15,
    acctExample: '100012345678',
    category: 'sfb',
  },
  {
    code: 'UJVN',
    name: 'Ujjivan Small Finance Bank',
    acctMin: 13,
    acctMax: 15,
    acctExample: '1234012345678',
    category: 'sfb',
  },
  {
    code: 'JSFB',
    name: 'Jana Small Finance Bank',
    acctMin: 10,
    acctMax: 16,
    category: 'sfb',
  },
  {
    code: 'SURY',
    name: 'Suryoday Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'ESMF',
    name: 'ESAF Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'UTKS',
    name: 'Utkarsh Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'CLBL',
    name: 'Capital Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'FSFB',
    name: 'Fincare Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'SMCB',
    name: 'Shivalik Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'UNTY',
    name: 'Unity Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },
  {
    code: 'NESF',
    name: 'North East Small Finance Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'sfb',
  },

  // ── Payments banks ─────────────────────────────────────────────────────────
  {
    code: 'PYTM',
    name: 'Paytm Payments Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'payments',
  },
  {
    code: 'AIRP',
    name: 'Airtel Payments Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'payments',
  },
  {
    code: 'IPOS',
    name: 'India Post Payments Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'payments',
  },
  {
    code: 'FINO',
    name: 'Fino Payments Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'payments',
  },
  {
    code: 'JIOP',
    name: 'Jio Payments Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'payments',
  },
  {
    code: 'NSPB',
    name: 'NSDL Payments Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'payments',
  },

  // ── Foreign banks (India operations) ───────────────────────────────────────
  {
    code: 'SCBL',
    name: 'Standard Chartered Bank',
    acctMin: 10,
    acctMax: 16,
    category: 'foreign',
  },
  {
    code: 'CITI',
    name: 'Citibank',
    acctMin: 10,
    acctMax: 12,
    category: 'foreign',
  },
  {
    code: 'HSBC',
    name: 'HSBC Bank',
    acctMin: 12,
    acctMax: 12,
    category: 'foreign',
  },
  {
    code: 'DEUT',
    name: 'Deutsche Bank',
    acctMin: 10,
    acctMax: 16,
    category: 'foreign',
  },
  {
    code: 'DBSS',
    name: 'DBS Bank India',
    acctMin: 10,
    acctMax: 16,
    category: 'foreign',
  },
  {
    code: 'BARC',
    name: 'Barclays Bank',
    acctMin: 10,
    acctMax: 16,
    category: 'foreign',
  },
  {
    code: 'BOFA',
    name: 'Bank of America',
    acctMin: 10,
    acctMax: 16,
    category: 'foreign',
  },
  {
    code: 'CHAS',
    name: 'JPMorgan Chase Bank',
    acctMin: 10,
    acctMax: 16,
    category: 'foreign',
  },

  // ── Co-operative banks ─────────────────────────────────────────────────────
  {
    code: 'SRCB',
    name: 'Saraswat Co-operative Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
  {
    code: 'COSB',
    name: 'Cosmos Co-operative Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
  {
    code: 'SVCB',
    name: 'SVC Co-operative Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
  {
    code: 'ABHY',
    name: 'Abhyudaya Co-operative Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
  {
    code: 'TJSB',
    name: 'TJSB Sahakari Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
  {
    code: 'BCBM',
    name: 'Bharat Co-operative Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
  {
    code: 'JSBP',
    name: 'Janata Sahakari Bank',
    acctMin: 9,
    acctMax: 18,
    category: 'coop',
  },
];
